// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Building.proto
// Protobuf Java Version: 4.27.2

package message;

public final class Building {
  private Building() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Building.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BuildingDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BuildingData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 建筑唯一ID
     * </pre>
     *
     * <code>string buildingUuid = 1;</code>
     * @return The buildingUuid.
     */
    java.lang.String getBuildingUuid();
    /**
     * <pre>
     * 建筑唯一ID
     * </pre>
     *
     * <code>string buildingUuid = 1;</code>
     * @return The bytes for buildingUuid.
     */
    com.google.protobuf.ByteString
        getBuildingUuidBytes();

    /**
     * <code>int32 buildingId = 2;</code>
     * @return The buildingId.
     */
    int getBuildingId();

    /**
     * <code>int32 position = 3;</code>
     * @return The position.
     */
    int getPosition();
  }
  /**
   * Protobuf type {@code BuildingData}
   */
  public static final class BuildingData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BuildingData)
      BuildingDataOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        BuildingData.class.getName());
    }
    // Use BuildingData.newBuilder() to construct.
    private BuildingData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BuildingData() {
      buildingUuid_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.Building.internal_static_BuildingData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.Building.internal_static_BuildingData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.Building.BuildingData.class, message.Building.BuildingData.Builder.class);
    }

    public static final int BUILDINGUUID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object buildingUuid_ = "";
    /**
     * <pre>
     * 建筑唯一ID
     * </pre>
     *
     * <code>string buildingUuid = 1;</code>
     * @return The buildingUuid.
     */
    @java.lang.Override
    public java.lang.String getBuildingUuid() {
      java.lang.Object ref = buildingUuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buildingUuid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 建筑唯一ID
     * </pre>
     *
     * <code>string buildingUuid = 1;</code>
     * @return The bytes for buildingUuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBuildingUuidBytes() {
      java.lang.Object ref = buildingUuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buildingUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BUILDINGID_FIELD_NUMBER = 2;
    private int buildingId_ = 0;
    /**
     * <code>int32 buildingId = 2;</code>
     * @return The buildingId.
     */
    @java.lang.Override
    public int getBuildingId() {
      return buildingId_;
    }

    public static final int POSITION_FIELD_NUMBER = 3;
    private int position_ = 0;
    /**
     * <code>int32 position = 3;</code>
     * @return The position.
     */
    @java.lang.Override
    public int getPosition() {
      return position_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(buildingUuid_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, buildingUuid_);
      }
      if (buildingId_ != 0) {
        output.writeInt32(2, buildingId_);
      }
      if (position_ != 0) {
        output.writeInt32(3, position_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(buildingUuid_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, buildingUuid_);
      }
      if (buildingId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, buildingId_);
      }
      if (position_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, position_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.Building.BuildingData)) {
        return super.equals(obj);
      }
      message.Building.BuildingData other = (message.Building.BuildingData) obj;

      if (!getBuildingUuid()
          .equals(other.getBuildingUuid())) return false;
      if (getBuildingId()
          != other.getBuildingId()) return false;
      if (getPosition()
          != other.getPosition()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BUILDINGUUID_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingUuid().hashCode();
      hash = (37 * hash) + BUILDINGID_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingId();
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.Building.BuildingData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Building.BuildingData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Building.BuildingData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Building.BuildingData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Building.BuildingData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Building.BuildingData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Building.BuildingData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Building.BuildingData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static message.Building.BuildingData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static message.Building.BuildingData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Building.BuildingData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Building.BuildingData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.Building.BuildingData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BuildingData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BuildingData)
        message.Building.BuildingDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.Building.internal_static_BuildingData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.Building.internal_static_BuildingData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.Building.BuildingData.class, message.Building.BuildingData.Builder.class);
      }

      // Construct using message.Building.BuildingData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        buildingUuid_ = "";
        buildingId_ = 0;
        position_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.Building.internal_static_BuildingData_descriptor;
      }

      @java.lang.Override
      public message.Building.BuildingData getDefaultInstanceForType() {
        return message.Building.BuildingData.getDefaultInstance();
      }

      @java.lang.Override
      public message.Building.BuildingData build() {
        message.Building.BuildingData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public message.Building.BuildingData buildPartial() {
        message.Building.BuildingData result = new message.Building.BuildingData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(message.Building.BuildingData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.buildingUuid_ = buildingUuid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.buildingId_ = buildingId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.position_ = position_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.Building.BuildingData) {
          return mergeFrom((message.Building.BuildingData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.Building.BuildingData other) {
        if (other == message.Building.BuildingData.getDefaultInstance()) return this;
        if (!other.getBuildingUuid().isEmpty()) {
          buildingUuid_ = other.buildingUuid_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getBuildingId() != 0) {
          setBuildingId(other.getBuildingId());
        }
        if (other.getPosition() != 0) {
          setPosition(other.getPosition());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                buildingUuid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                buildingId_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                position_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object buildingUuid_ = "";
      /**
       * <pre>
       * 建筑唯一ID
       * </pre>
       *
       * <code>string buildingUuid = 1;</code>
       * @return The buildingUuid.
       */
      public java.lang.String getBuildingUuid() {
        java.lang.Object ref = buildingUuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          buildingUuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 建筑唯一ID
       * </pre>
       *
       * <code>string buildingUuid = 1;</code>
       * @return The bytes for buildingUuid.
       */
      public com.google.protobuf.ByteString
          getBuildingUuidBytes() {
        java.lang.Object ref = buildingUuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buildingUuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 建筑唯一ID
       * </pre>
       *
       * <code>string buildingUuid = 1;</code>
       * @param value The buildingUuid to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingUuid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        buildingUuid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 建筑唯一ID
       * </pre>
       *
       * <code>string buildingUuid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingUuid() {
        buildingUuid_ = getDefaultInstance().getBuildingUuid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 建筑唯一ID
       * </pre>
       *
       * <code>string buildingUuid = 1;</code>
       * @param value The bytes for buildingUuid to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        buildingUuid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int buildingId_ ;
      /**
       * <code>int32 buildingId = 2;</code>
       * @return The buildingId.
       */
      @java.lang.Override
      public int getBuildingId() {
        return buildingId_;
      }
      /**
       * <code>int32 buildingId = 2;</code>
       * @param value The buildingId to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingId(int value) {

        buildingId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 buildingId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        buildingId_ = 0;
        onChanged();
        return this;
      }

      private int position_ ;
      /**
       * <code>int32 position = 3;</code>
       * @return The position.
       */
      @java.lang.Override
      public int getPosition() {
        return position_;
      }
      /**
       * <code>int32 position = 3;</code>
       * @param value The position to set.
       * @return This builder for chaining.
       */
      public Builder setPosition(int value) {

        position_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 position = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosition() {
        bitField0_ = (bitField0_ & ~0x00000004);
        position_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BuildingData)
    }

    // @@protoc_insertion_point(class_scope:BuildingData)
    private static final message.Building.BuildingData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.Building.BuildingData();
    }

    public static message.Building.BuildingData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BuildingData>
        PARSER = new com.google.protobuf.AbstractParser<BuildingData>() {
      @java.lang.Override
      public BuildingData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BuildingData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BuildingData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public message.Building.BuildingData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BuildingConstructReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BuildingConstructReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 buildingId = 1;</code>
     * @return The buildingId.
     */
    int getBuildingId();

    /**
     * <code>int32 position = 2;</code>
     * @return The position.
     */
    int getPosition();
  }
  /**
   * Protobuf type {@code BuildingConstructReq}
   */
  public static final class BuildingConstructReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BuildingConstructReq)
      BuildingConstructReqOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        BuildingConstructReq.class.getName());
    }
    // Use BuildingConstructReq.newBuilder() to construct.
    private BuildingConstructReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BuildingConstructReq() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.Building.internal_static_BuildingConstructReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.Building.internal_static_BuildingConstructReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.Building.BuildingConstructReq.class, message.Building.BuildingConstructReq.Builder.class);
    }

    public static final int BUILDINGID_FIELD_NUMBER = 1;
    private int buildingId_ = 0;
    /**
     * <code>int32 buildingId = 1;</code>
     * @return The buildingId.
     */
    @java.lang.Override
    public int getBuildingId() {
      return buildingId_;
    }

    public static final int POSITION_FIELD_NUMBER = 2;
    private int position_ = 0;
    /**
     * <code>int32 position = 2;</code>
     * @return The position.
     */
    @java.lang.Override
    public int getPosition() {
      return position_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (buildingId_ != 0) {
        output.writeInt32(1, buildingId_);
      }
      if (position_ != 0) {
        output.writeInt32(2, position_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (buildingId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, buildingId_);
      }
      if (position_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, position_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.Building.BuildingConstructReq)) {
        return super.equals(obj);
      }
      message.Building.BuildingConstructReq other = (message.Building.BuildingConstructReq) obj;

      if (getBuildingId()
          != other.getBuildingId()) return false;
      if (getPosition()
          != other.getPosition()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BUILDINGID_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingId();
      hash = (37 * hash) + POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getPosition();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.Building.BuildingConstructReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Building.BuildingConstructReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Building.BuildingConstructReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Building.BuildingConstructReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Building.BuildingConstructReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Building.BuildingConstructReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Building.BuildingConstructReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Building.BuildingConstructReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static message.Building.BuildingConstructReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static message.Building.BuildingConstructReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Building.BuildingConstructReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Building.BuildingConstructReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.Building.BuildingConstructReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BuildingConstructReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BuildingConstructReq)
        message.Building.BuildingConstructReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.Building.internal_static_BuildingConstructReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.Building.internal_static_BuildingConstructReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.Building.BuildingConstructReq.class, message.Building.BuildingConstructReq.Builder.class);
      }

      // Construct using message.Building.BuildingConstructReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        buildingId_ = 0;
        position_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.Building.internal_static_BuildingConstructReq_descriptor;
      }

      @java.lang.Override
      public message.Building.BuildingConstructReq getDefaultInstanceForType() {
        return message.Building.BuildingConstructReq.getDefaultInstance();
      }

      @java.lang.Override
      public message.Building.BuildingConstructReq build() {
        message.Building.BuildingConstructReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public message.Building.BuildingConstructReq buildPartial() {
        message.Building.BuildingConstructReq result = new message.Building.BuildingConstructReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(message.Building.BuildingConstructReq result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.buildingId_ = buildingId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.position_ = position_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.Building.BuildingConstructReq) {
          return mergeFrom((message.Building.BuildingConstructReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.Building.BuildingConstructReq other) {
        if (other == message.Building.BuildingConstructReq.getDefaultInstance()) return this;
        if (other.getBuildingId() != 0) {
          setBuildingId(other.getBuildingId());
        }
        if (other.getPosition() != 0) {
          setPosition(other.getPosition());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                buildingId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                position_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int buildingId_ ;
      /**
       * <code>int32 buildingId = 1;</code>
       * @return The buildingId.
       */
      @java.lang.Override
      public int getBuildingId() {
        return buildingId_;
      }
      /**
       * <code>int32 buildingId = 1;</code>
       * @param value The buildingId to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingId(int value) {

        buildingId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 buildingId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        buildingId_ = 0;
        onChanged();
        return this;
      }

      private int position_ ;
      /**
       * <code>int32 position = 2;</code>
       * @return The position.
       */
      @java.lang.Override
      public int getPosition() {
        return position_;
      }
      /**
       * <code>int32 position = 2;</code>
       * @param value The position to set.
       * @return This builder for chaining.
       */
      public Builder setPosition(int value) {

        position_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 position = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPosition() {
        bitField0_ = (bitField0_ & ~0x00000002);
        position_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BuildingConstructReq)
    }

    // @@protoc_insertion_point(class_scope:BuildingConstructReq)
    private static final message.Building.BuildingConstructReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.Building.BuildingConstructReq();
    }

    public static message.Building.BuildingConstructReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BuildingConstructReq>
        PARSER = new com.google.protobuf.AbstractParser<BuildingConstructReq>() {
      @java.lang.Override
      public BuildingConstructReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BuildingConstructReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BuildingConstructReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public message.Building.BuildingConstructReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BuildingLevelUpReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BuildingLevelUpReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 建筑唯一ID
     * </pre>
     *
     * <code>string buildingUuid = 1;</code>
     * @return The buildingUuid.
     */
    java.lang.String getBuildingUuid();
    /**
     * <pre>
     * 建筑唯一ID
     * </pre>
     *
     * <code>string buildingUuid = 1;</code>
     * @return The bytes for buildingUuid.
     */
    com.google.protobuf.ByteString
        getBuildingUuidBytes();
  }
  /**
   * Protobuf type {@code BuildingLevelUpReq}
   */
  public static final class BuildingLevelUpReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BuildingLevelUpReq)
      BuildingLevelUpReqOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        BuildingLevelUpReq.class.getName());
    }
    // Use BuildingLevelUpReq.newBuilder() to construct.
    private BuildingLevelUpReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BuildingLevelUpReq() {
      buildingUuid_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.Building.internal_static_BuildingLevelUpReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.Building.internal_static_BuildingLevelUpReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.Building.BuildingLevelUpReq.class, message.Building.BuildingLevelUpReq.Builder.class);
    }

    public static final int BUILDINGUUID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object buildingUuid_ = "";
    /**
     * <pre>
     * 建筑唯一ID
     * </pre>
     *
     * <code>string buildingUuid = 1;</code>
     * @return The buildingUuid.
     */
    @java.lang.Override
    public java.lang.String getBuildingUuid() {
      java.lang.Object ref = buildingUuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        buildingUuid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 建筑唯一ID
     * </pre>
     *
     * <code>string buildingUuid = 1;</code>
     * @return The bytes for buildingUuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBuildingUuidBytes() {
      java.lang.Object ref = buildingUuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buildingUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(buildingUuid_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, buildingUuid_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(buildingUuid_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, buildingUuid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.Building.BuildingLevelUpReq)) {
        return super.equals(obj);
      }
      message.Building.BuildingLevelUpReq other = (message.Building.BuildingLevelUpReq) obj;

      if (!getBuildingUuid()
          .equals(other.getBuildingUuid())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BUILDINGUUID_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingUuid().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.Building.BuildingLevelUpReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Building.BuildingLevelUpReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Building.BuildingLevelUpReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Building.BuildingLevelUpReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Building.BuildingLevelUpReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Building.BuildingLevelUpReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Building.BuildingLevelUpReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Building.BuildingLevelUpReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static message.Building.BuildingLevelUpReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static message.Building.BuildingLevelUpReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Building.BuildingLevelUpReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Building.BuildingLevelUpReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.Building.BuildingLevelUpReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BuildingLevelUpReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BuildingLevelUpReq)
        message.Building.BuildingLevelUpReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.Building.internal_static_BuildingLevelUpReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.Building.internal_static_BuildingLevelUpReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.Building.BuildingLevelUpReq.class, message.Building.BuildingLevelUpReq.Builder.class);
      }

      // Construct using message.Building.BuildingLevelUpReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        buildingUuid_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.Building.internal_static_BuildingLevelUpReq_descriptor;
      }

      @java.lang.Override
      public message.Building.BuildingLevelUpReq getDefaultInstanceForType() {
        return message.Building.BuildingLevelUpReq.getDefaultInstance();
      }

      @java.lang.Override
      public message.Building.BuildingLevelUpReq build() {
        message.Building.BuildingLevelUpReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public message.Building.BuildingLevelUpReq buildPartial() {
        message.Building.BuildingLevelUpReq result = new message.Building.BuildingLevelUpReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(message.Building.BuildingLevelUpReq result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.buildingUuid_ = buildingUuid_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.Building.BuildingLevelUpReq) {
          return mergeFrom((message.Building.BuildingLevelUpReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.Building.BuildingLevelUpReq other) {
        if (other == message.Building.BuildingLevelUpReq.getDefaultInstance()) return this;
        if (!other.getBuildingUuid().isEmpty()) {
          buildingUuid_ = other.buildingUuid_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                buildingUuid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object buildingUuid_ = "";
      /**
       * <pre>
       * 建筑唯一ID
       * </pre>
       *
       * <code>string buildingUuid = 1;</code>
       * @return The buildingUuid.
       */
      public java.lang.String getBuildingUuid() {
        java.lang.Object ref = buildingUuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          buildingUuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 建筑唯一ID
       * </pre>
       *
       * <code>string buildingUuid = 1;</code>
       * @return The bytes for buildingUuid.
       */
      public com.google.protobuf.ByteString
          getBuildingUuidBytes() {
        java.lang.Object ref = buildingUuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buildingUuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 建筑唯一ID
       * </pre>
       *
       * <code>string buildingUuid = 1;</code>
       * @param value The buildingUuid to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingUuid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        buildingUuid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 建筑唯一ID
       * </pre>
       *
       * <code>string buildingUuid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBuildingUuid() {
        buildingUuid_ = getDefaultInstance().getBuildingUuid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 建筑唯一ID
       * </pre>
       *
       * <code>string buildingUuid = 1;</code>
       * @param value The bytes for buildingUuid to set.
       * @return This builder for chaining.
       */
      public Builder setBuildingUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        buildingUuid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BuildingLevelUpReq)
    }

    // @@protoc_insertion_point(class_scope:BuildingLevelUpReq)
    private static final message.Building.BuildingLevelUpReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.Building.BuildingLevelUpReq();
    }

    public static message.Building.BuildingLevelUpReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BuildingLevelUpReq>
        PARSER = new com.google.protobuf.AbstractParser<BuildingLevelUpReq>() {
      @java.lang.Override
      public BuildingLevelUpReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BuildingLevelUpReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BuildingLevelUpReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public message.Building.BuildingLevelUpReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BuildingUpdateRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BuildingUpdateResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 建筑信息
     * </pre>
     *
     * <code>.BuildingData buildingData = 1;</code>
     * @return Whether the buildingData field is set.
     */
    boolean hasBuildingData();
    /**
     * <pre>
     * 建筑信息
     * </pre>
     *
     * <code>.BuildingData buildingData = 1;</code>
     * @return The buildingData.
     */
    message.Building.BuildingData getBuildingData();
    /**
     * <pre>
     * 建筑信息
     * </pre>
     *
     * <code>.BuildingData buildingData = 1;</code>
     */
    message.Building.BuildingDataOrBuilder getBuildingDataOrBuilder();

    /**
     * <pre>
     * 更新原因
     * </pre>
     *
     * <code>int32 reason = 2;</code>
     * @return The reason.
     */
    int getReason();
  }
  /**
   * Protobuf type {@code BuildingUpdateResp}
   */
  public static final class BuildingUpdateResp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BuildingUpdateResp)
      BuildingUpdateRespOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        BuildingUpdateResp.class.getName());
    }
    // Use BuildingUpdateResp.newBuilder() to construct.
    private BuildingUpdateResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BuildingUpdateResp() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.Building.internal_static_BuildingUpdateResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.Building.internal_static_BuildingUpdateResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.Building.BuildingUpdateResp.class, message.Building.BuildingUpdateResp.Builder.class);
    }

    private int bitField0_;
    public static final int BUILDINGDATA_FIELD_NUMBER = 1;
    private message.Building.BuildingData buildingData_;
    /**
     * <pre>
     * 建筑信息
     * </pre>
     *
     * <code>.BuildingData buildingData = 1;</code>
     * @return Whether the buildingData field is set.
     */
    @java.lang.Override
    public boolean hasBuildingData() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 建筑信息
     * </pre>
     *
     * <code>.BuildingData buildingData = 1;</code>
     * @return The buildingData.
     */
    @java.lang.Override
    public message.Building.BuildingData getBuildingData() {
      return buildingData_ == null ? message.Building.BuildingData.getDefaultInstance() : buildingData_;
    }
    /**
     * <pre>
     * 建筑信息
     * </pre>
     *
     * <code>.BuildingData buildingData = 1;</code>
     */
    @java.lang.Override
    public message.Building.BuildingDataOrBuilder getBuildingDataOrBuilder() {
      return buildingData_ == null ? message.Building.BuildingData.getDefaultInstance() : buildingData_;
    }

    public static final int REASON_FIELD_NUMBER = 2;
    private int reason_ = 0;
    /**
     * <pre>
     * 更新原因
     * </pre>
     *
     * <code>int32 reason = 2;</code>
     * @return The reason.
     */
    @java.lang.Override
    public int getReason() {
      return reason_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getBuildingData());
      }
      if (reason_ != 0) {
        output.writeInt32(2, reason_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBuildingData());
      }
      if (reason_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, reason_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.Building.BuildingUpdateResp)) {
        return super.equals(obj);
      }
      message.Building.BuildingUpdateResp other = (message.Building.BuildingUpdateResp) obj;

      if (hasBuildingData() != other.hasBuildingData()) return false;
      if (hasBuildingData()) {
        if (!getBuildingData()
            .equals(other.getBuildingData())) return false;
      }
      if (getReason()
          != other.getReason()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBuildingData()) {
        hash = (37 * hash) + BUILDINGDATA_FIELD_NUMBER;
        hash = (53 * hash) + getBuildingData().hashCode();
      }
      hash = (37 * hash) + REASON_FIELD_NUMBER;
      hash = (53 * hash) + getReason();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.Building.BuildingUpdateResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Building.BuildingUpdateResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Building.BuildingUpdateResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Building.BuildingUpdateResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Building.BuildingUpdateResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Building.BuildingUpdateResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Building.BuildingUpdateResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Building.BuildingUpdateResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static message.Building.BuildingUpdateResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static message.Building.BuildingUpdateResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Building.BuildingUpdateResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Building.BuildingUpdateResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.Building.BuildingUpdateResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BuildingUpdateResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BuildingUpdateResp)
        message.Building.BuildingUpdateRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.Building.internal_static_BuildingUpdateResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.Building.internal_static_BuildingUpdateResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.Building.BuildingUpdateResp.class, message.Building.BuildingUpdateResp.Builder.class);
      }

      // Construct using message.Building.BuildingUpdateResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getBuildingDataFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        buildingData_ = null;
        if (buildingDataBuilder_ != null) {
          buildingDataBuilder_.dispose();
          buildingDataBuilder_ = null;
        }
        reason_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.Building.internal_static_BuildingUpdateResp_descriptor;
      }

      @java.lang.Override
      public message.Building.BuildingUpdateResp getDefaultInstanceForType() {
        return message.Building.BuildingUpdateResp.getDefaultInstance();
      }

      @java.lang.Override
      public message.Building.BuildingUpdateResp build() {
        message.Building.BuildingUpdateResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public message.Building.BuildingUpdateResp buildPartial() {
        message.Building.BuildingUpdateResp result = new message.Building.BuildingUpdateResp(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(message.Building.BuildingUpdateResp result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.buildingData_ = buildingDataBuilder_ == null
              ? buildingData_
              : buildingDataBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.reason_ = reason_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.Building.BuildingUpdateResp) {
          return mergeFrom((message.Building.BuildingUpdateResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.Building.BuildingUpdateResp other) {
        if (other == message.Building.BuildingUpdateResp.getDefaultInstance()) return this;
        if (other.hasBuildingData()) {
          mergeBuildingData(other.getBuildingData());
        }
        if (other.getReason() != 0) {
          setReason(other.getReason());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getBuildingDataFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                reason_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private message.Building.BuildingData buildingData_;
      private com.google.protobuf.SingleFieldBuilder<
          message.Building.BuildingData, message.Building.BuildingData.Builder, message.Building.BuildingDataOrBuilder> buildingDataBuilder_;
      /**
       * <pre>
       * 建筑信息
       * </pre>
       *
       * <code>.BuildingData buildingData = 1;</code>
       * @return Whether the buildingData field is set.
       */
      public boolean hasBuildingData() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 建筑信息
       * </pre>
       *
       * <code>.BuildingData buildingData = 1;</code>
       * @return The buildingData.
       */
      public message.Building.BuildingData getBuildingData() {
        if (buildingDataBuilder_ == null) {
          return buildingData_ == null ? message.Building.BuildingData.getDefaultInstance() : buildingData_;
        } else {
          return buildingDataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 建筑信息
       * </pre>
       *
       * <code>.BuildingData buildingData = 1;</code>
       */
      public Builder setBuildingData(message.Building.BuildingData value) {
        if (buildingDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          buildingData_ = value;
        } else {
          buildingDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 建筑信息
       * </pre>
       *
       * <code>.BuildingData buildingData = 1;</code>
       */
      public Builder setBuildingData(
          message.Building.BuildingData.Builder builderForValue) {
        if (buildingDataBuilder_ == null) {
          buildingData_ = builderForValue.build();
        } else {
          buildingDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 建筑信息
       * </pre>
       *
       * <code>.BuildingData buildingData = 1;</code>
       */
      public Builder mergeBuildingData(message.Building.BuildingData value) {
        if (buildingDataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            buildingData_ != null &&
            buildingData_ != message.Building.BuildingData.getDefaultInstance()) {
            getBuildingDataBuilder().mergeFrom(value);
          } else {
            buildingData_ = value;
          }
        } else {
          buildingDataBuilder_.mergeFrom(value);
        }
        if (buildingData_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * 建筑信息
       * </pre>
       *
       * <code>.BuildingData buildingData = 1;</code>
       */
      public Builder clearBuildingData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        buildingData_ = null;
        if (buildingDataBuilder_ != null) {
          buildingDataBuilder_.dispose();
          buildingDataBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 建筑信息
       * </pre>
       *
       * <code>.BuildingData buildingData = 1;</code>
       */
      public message.Building.BuildingData.Builder getBuildingDataBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBuildingDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 建筑信息
       * </pre>
       *
       * <code>.BuildingData buildingData = 1;</code>
       */
      public message.Building.BuildingDataOrBuilder getBuildingDataOrBuilder() {
        if (buildingDataBuilder_ != null) {
          return buildingDataBuilder_.getMessageOrBuilder();
        } else {
          return buildingData_ == null ?
              message.Building.BuildingData.getDefaultInstance() : buildingData_;
        }
      }
      /**
       * <pre>
       * 建筑信息
       * </pre>
       *
       * <code>.BuildingData buildingData = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          message.Building.BuildingData, message.Building.BuildingData.Builder, message.Building.BuildingDataOrBuilder> 
          getBuildingDataFieldBuilder() {
        if (buildingDataBuilder_ == null) {
          buildingDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              message.Building.BuildingData, message.Building.BuildingData.Builder, message.Building.BuildingDataOrBuilder>(
                  getBuildingData(),
                  getParentForChildren(),
                  isClean());
          buildingData_ = null;
        }
        return buildingDataBuilder_;
      }

      private int reason_ ;
      /**
       * <pre>
       * 更新原因
       * </pre>
       *
       * <code>int32 reason = 2;</code>
       * @return The reason.
       */
      @java.lang.Override
      public int getReason() {
        return reason_;
      }
      /**
       * <pre>
       * 更新原因
       * </pre>
       *
       * <code>int32 reason = 2;</code>
       * @param value The reason to set.
       * @return This builder for chaining.
       */
      public Builder setReason(int value) {

        reason_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 更新原因
       * </pre>
       *
       * <code>int32 reason = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReason() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reason_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BuildingUpdateResp)
    }

    // @@protoc_insertion_point(class_scope:BuildingUpdateResp)
    private static final message.Building.BuildingUpdateResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.Building.BuildingUpdateResp();
    }

    public static message.Building.BuildingUpdateResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BuildingUpdateResp>
        PARSER = new com.google.protobuf.AbstractParser<BuildingUpdateResp>() {
      @java.lang.Override
      public BuildingUpdateResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BuildingUpdateResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BuildingUpdateResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public message.Building.BuildingUpdateResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BuildingData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BuildingData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BuildingConstructReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BuildingConstructReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BuildingLevelUpReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BuildingLevelUpReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BuildingUpdateResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BuildingUpdateResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Building.proto\"J\n\014BuildingData\022\024\n\014buil" +
      "dingUuid\030\001 \001(\t\022\022\n\nbuildingId\030\002 \001(\005\022\020\n\010po" +
      "sition\030\003 \001(\005\"<\n\024BuildingConstructReq\022\022\n\n" +
      "buildingId\030\001 \001(\005\022\020\n\010position\030\002 \001(\005\"*\n\022Bu" +
      "ildingLevelUpReq\022\024\n\014buildingUuid\030\001 \001(\t\"I" +
      "\n\022BuildingUpdateResp\022#\n\014buildingData\030\001 \001" +
      "(\0132\r.BuildingData\022\016\n\006reason\030\002 \001(\005B\t\n\007mes" +
      "sageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BuildingData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BuildingData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BuildingData_descriptor,
        new java.lang.String[] { "BuildingUuid", "BuildingId", "Position", });
    internal_static_BuildingConstructReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BuildingConstructReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BuildingConstructReq_descriptor,
        new java.lang.String[] { "BuildingId", "Position", });
    internal_static_BuildingLevelUpReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_BuildingLevelUpReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BuildingLevelUpReq_descriptor,
        new java.lang.String[] { "BuildingUuid", });
    internal_static_BuildingUpdateResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_BuildingUpdateResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BuildingUpdateResp_descriptor,
        new java.lang.String[] { "BuildingData", "Reason", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
