// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Login.proto
// Protobuf Java Version: 4.27.2

package message;

public final class Login {
  private Login() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Login.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>string account = 1;</code>
     * @return The account.
     */
    java.lang.String getAccount();
    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>string account = 1;</code>
     * @return The bytes for account.
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <pre>
     * 密码
     * </pre>
     *
     * <code>string pwd = 2;</code>
     * @return The pwd.
     */
    java.lang.String getPwd();
    /**
     * <pre>
     * 密码
     * </pre>
     *
     * <code>string pwd = 2;</code>
     * @return The bytes for pwd.
     */
    com.google.protobuf.ByteString
        getPwdBytes();
  }
  /**
   * Protobuf type {@code LoginReq}
   */
  public static final class LoginReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:LoginReq)
      LoginReqOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        LoginReq.class.getName());
    }
    // Use LoginReq.newBuilder() to construct.
    private LoginReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private LoginReq() {
      account_ = "";
      pwd_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.Login.internal_static_LoginReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.Login.internal_static_LoginReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.Login.LoginReq.class, message.Login.LoginReq.Builder.class);
    }

    public static final int ACCOUNT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object account_ = "";
    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>string account = 1;</code>
     * @return The account.
     */
    @java.lang.Override
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        account_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>string account = 1;</code>
     * @return The bytes for account.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PWD_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object pwd_ = "";
    /**
     * <pre>
     * 密码
     * </pre>
     *
     * <code>string pwd = 2;</code>
     * @return The pwd.
     */
    @java.lang.Override
    public java.lang.String getPwd() {
      java.lang.Object ref = pwd_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pwd_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 密码
     * </pre>
     *
     * <code>string pwd = 2;</code>
     * @return The bytes for pwd.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPwdBytes() {
      java.lang.Object ref = pwd_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(account_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, account_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pwd_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, pwd_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(account_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, account_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(pwd_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, pwd_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.Login.LoginReq)) {
        return super.equals(obj);
      }
      message.Login.LoginReq other = (message.Login.LoginReq) obj;

      if (!getAccount()
          .equals(other.getAccount())) return false;
      if (!getPwd()
          .equals(other.getPwd())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
      hash = (37 * hash) + PWD_FIELD_NUMBER;
      hash = (53 * hash) + getPwd().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.Login.LoginReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Login.LoginReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Login.LoginReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Login.LoginReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Login.LoginReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Login.LoginReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Login.LoginReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Login.LoginReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static message.Login.LoginReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static message.Login.LoginReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Login.LoginReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Login.LoginReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.Login.LoginReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginReq)
        message.Login.LoginReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.Login.internal_static_LoginReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.Login.internal_static_LoginReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.Login.LoginReq.class, message.Login.LoginReq.Builder.class);
      }

      // Construct using message.Login.LoginReq.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        account_ = "";
        pwd_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.Login.internal_static_LoginReq_descriptor;
      }

      @java.lang.Override
      public message.Login.LoginReq getDefaultInstanceForType() {
        return message.Login.LoginReq.getDefaultInstance();
      }

      @java.lang.Override
      public message.Login.LoginReq build() {
        message.Login.LoginReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public message.Login.LoginReq buildPartial() {
        message.Login.LoginReq result = new message.Login.LoginReq(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(message.Login.LoginReq result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.account_ = account_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.pwd_ = pwd_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.Login.LoginReq) {
          return mergeFrom((message.Login.LoginReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.Login.LoginReq other) {
        if (other == message.Login.LoginReq.getDefaultInstance()) return this;
        if (!other.getAccount().isEmpty()) {
          account_ = other.account_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getPwd().isEmpty()) {
          pwd_ = other.pwd_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                account_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                pwd_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object account_ = "";
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>string account = 1;</code>
       * @return The account.
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>string account = 1;</code>
       * @return The bytes for account.
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>string account = 1;</code>
       * @param value The account to set.
       * @return This builder for chaining.
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        account_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>string account = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccount() {
        account_ = getDefaultInstance().getAccount();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>string account = 1;</code>
       * @param value The bytes for account to set.
       * @return This builder for chaining.
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        account_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object pwd_ = "";
      /**
       * <pre>
       * 密码
       * </pre>
       *
       * <code>string pwd = 2;</code>
       * @return The pwd.
       */
      public java.lang.String getPwd() {
        java.lang.Object ref = pwd_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pwd_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 密码
       * </pre>
       *
       * <code>string pwd = 2;</code>
       * @return The bytes for pwd.
       */
      public com.google.protobuf.ByteString
          getPwdBytes() {
        java.lang.Object ref = pwd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pwd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 密码
       * </pre>
       *
       * <code>string pwd = 2;</code>
       * @param value The pwd to set.
       * @return This builder for chaining.
       */
      public Builder setPwd(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        pwd_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 密码
       * </pre>
       *
       * <code>string pwd = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPwd() {
        pwd_ = getDefaultInstance().getPwd();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 密码
       * </pre>
       *
       * <code>string pwd = 2;</code>
       * @param value The bytes for pwd to set.
       * @return This builder for chaining.
       */
      public Builder setPwdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        pwd_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LoginReq)
    }

    // @@protoc_insertion_point(class_scope:LoginReq)
    private static final message.Login.LoginReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.Login.LoginReq();
    }

    public static message.Login.LoginReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginReq>
        PARSER = new com.google.protobuf.AbstractParser<LoginReq>() {
      @java.lang.Override
      public LoginReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LoginReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public message.Login.LoginReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LoginResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 返回码
     * </pre>
     *
     * <code>int32 rltCode = 1;</code>
     * @return The rltCode.
     */
    int getRltCode();

    /**
     * <pre>
     * 服务器当前时间
     * </pre>
     *
     * <code>int64 serverTime = 2;</code>
     * @return The serverTime.
     */
    long getServerTime();

    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>string account = 3;</code>
     * @return The account.
     */
    java.lang.String getAccount();
    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>string account = 3;</code>
     * @return The bytes for account.
     */
    com.google.protobuf.ByteString
        getAccountBytes();

    /**
     * <pre>
     * 角色ID
     * </pre>
     *
     * <code>string playerId = 4;</code>
     * @return The playerId.
     */
    java.lang.String getPlayerId();
    /**
     * <pre>
     * 角色ID
     * </pre>
     *
     * <code>string playerId = 4;</code>
     * @return The bytes for playerId.
     */
    com.google.protobuf.ByteString
        getPlayerIdBytes();
  }
  /**
   * Protobuf type {@code LoginResp}
   */
  public static final class LoginResp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:LoginResp)
      LoginRespOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        LoginResp.class.getName());
    }
    // Use LoginResp.newBuilder() to construct.
    private LoginResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private LoginResp() {
      account_ = "";
      playerId_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.Login.internal_static_LoginResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.Login.internal_static_LoginResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.Login.LoginResp.class, message.Login.LoginResp.Builder.class);
    }

    public static final int RLTCODE_FIELD_NUMBER = 1;
    private int rltCode_ = 0;
    /**
     * <pre>
     * 返回码
     * </pre>
     *
     * <code>int32 rltCode = 1;</code>
     * @return The rltCode.
     */
    @java.lang.Override
    public int getRltCode() {
      return rltCode_;
    }

    public static final int SERVERTIME_FIELD_NUMBER = 2;
    private long serverTime_ = 0L;
    /**
     * <pre>
     * 服务器当前时间
     * </pre>
     *
     * <code>int64 serverTime = 2;</code>
     * @return The serverTime.
     */
    @java.lang.Override
    public long getServerTime() {
      return serverTime_;
    }

    public static final int ACCOUNT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object account_ = "";
    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>string account = 3;</code>
     * @return The account.
     */
    @java.lang.Override
    public java.lang.String getAccount() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        account_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 账号
     * </pre>
     *
     * <code>string account = 3;</code>
     * @return The bytes for account.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccountBytes() {
      java.lang.Object ref = account_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        account_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYERID_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object playerId_ = "";
    /**
     * <pre>
     * 角色ID
     * </pre>
     *
     * <code>string playerId = 4;</code>
     * @return The playerId.
     */
    @java.lang.Override
    public java.lang.String getPlayerId() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 角色ID
     * </pre>
     *
     * <code>string playerId = 4;</code>
     * @return The bytes for playerId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlayerIdBytes() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rltCode_ != 0) {
        output.writeInt32(1, rltCode_);
      }
      if (serverTime_ != 0L) {
        output.writeInt64(2, serverTime_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(account_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, account_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, playerId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rltCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rltCode_);
      }
      if (serverTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, serverTime_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(account_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, account_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, playerId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.Login.LoginResp)) {
        return super.equals(obj);
      }
      message.Login.LoginResp other = (message.Login.LoginResp) obj;

      if (getRltCode()
          != other.getRltCode()) return false;
      if (getServerTime()
          != other.getServerTime()) return false;
      if (!getAccount()
          .equals(other.getAccount())) return false;
      if (!getPlayerId()
          .equals(other.getPlayerId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RLTCODE_FIELD_NUMBER;
      hash = (53 * hash) + getRltCode();
      hash = (37 * hash) + SERVERTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getServerTime());
      hash = (37 * hash) + ACCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAccount().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.Login.LoginResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Login.LoginResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Login.LoginResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Login.LoginResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Login.LoginResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Login.LoginResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Login.LoginResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Login.LoginResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static message.Login.LoginResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static message.Login.LoginResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Login.LoginResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Login.LoginResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.Login.LoginResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LoginResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LoginResp)
        message.Login.LoginRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.Login.internal_static_LoginResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.Login.internal_static_LoginResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.Login.LoginResp.class, message.Login.LoginResp.Builder.class);
      }

      // Construct using message.Login.LoginResp.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        rltCode_ = 0;
        serverTime_ = 0L;
        account_ = "";
        playerId_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.Login.internal_static_LoginResp_descriptor;
      }

      @java.lang.Override
      public message.Login.LoginResp getDefaultInstanceForType() {
        return message.Login.LoginResp.getDefaultInstance();
      }

      @java.lang.Override
      public message.Login.LoginResp build() {
        message.Login.LoginResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public message.Login.LoginResp buildPartial() {
        message.Login.LoginResp result = new message.Login.LoginResp(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(message.Login.LoginResp result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.rltCode_ = rltCode_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.serverTime_ = serverTime_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.account_ = account_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.playerId_ = playerId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.Login.LoginResp) {
          return mergeFrom((message.Login.LoginResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.Login.LoginResp other) {
        if (other == message.Login.LoginResp.getDefaultInstance()) return this;
        if (other.getRltCode() != 0) {
          setRltCode(other.getRltCode());
        }
        if (other.getServerTime() != 0L) {
          setServerTime(other.getServerTime());
        }
        if (!other.getAccount().isEmpty()) {
          account_ = other.account_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getPlayerId().isEmpty()) {
          playerId_ = other.playerId_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                rltCode_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                serverTime_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                account_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                playerId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int rltCode_ ;
      /**
       * <pre>
       * 返回码
       * </pre>
       *
       * <code>int32 rltCode = 1;</code>
       * @return The rltCode.
       */
      @java.lang.Override
      public int getRltCode() {
        return rltCode_;
      }
      /**
       * <pre>
       * 返回码
       * </pre>
       *
       * <code>int32 rltCode = 1;</code>
       * @param value The rltCode to set.
       * @return This builder for chaining.
       */
      public Builder setRltCode(int value) {

        rltCode_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 返回码
       * </pre>
       *
       * <code>int32 rltCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRltCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rltCode_ = 0;
        onChanged();
        return this;
      }

      private long serverTime_ ;
      /**
       * <pre>
       * 服务器当前时间
       * </pre>
       *
       * <code>int64 serverTime = 2;</code>
       * @return The serverTime.
       */
      @java.lang.Override
      public long getServerTime() {
        return serverTime_;
      }
      /**
       * <pre>
       * 服务器当前时间
       * </pre>
       *
       * <code>int64 serverTime = 2;</code>
       * @param value The serverTime to set.
       * @return This builder for chaining.
       */
      public Builder setServerTime(long value) {

        serverTime_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 服务器当前时间
       * </pre>
       *
       * <code>int64 serverTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object account_ = "";
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>string account = 3;</code>
       * @return The account.
       */
      public java.lang.String getAccount() {
        java.lang.Object ref = account_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          account_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>string account = 3;</code>
       * @return The bytes for account.
       */
      public com.google.protobuf.ByteString
          getAccountBytes() {
        java.lang.Object ref = account_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          account_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>string account = 3;</code>
       * @param value The account to set.
       * @return This builder for chaining.
       */
      public Builder setAccount(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        account_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>string account = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccount() {
        account_ = getDefaultInstance().getAccount();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 账号
       * </pre>
       *
       * <code>string account = 3;</code>
       * @param value The bytes for account to set.
       * @return This builder for chaining.
       */
      public Builder setAccountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        account_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object playerId_ = "";
      /**
       * <pre>
       * 角色ID
       * </pre>
       *
       * <code>string playerId = 4;</code>
       * @return The playerId.
       */
      public java.lang.String getPlayerId() {
        java.lang.Object ref = playerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 角色ID
       * </pre>
       *
       * <code>string playerId = 4;</code>
       * @return The bytes for playerId.
       */
      public com.google.protobuf.ByteString
          getPlayerIdBytes() {
        java.lang.Object ref = playerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 角色ID
       * </pre>
       *
       * <code>string playerId = 4;</code>
       * @param value The playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        playerId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 角色ID
       * </pre>
       *
       * <code>string playerId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerId() {
        playerId_ = getDefaultInstance().getPlayerId();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 角色ID
       * </pre>
       *
       * <code>string playerId = 4;</code>
       * @param value The bytes for playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        playerId_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LoginResp)
    }

    // @@protoc_insertion_point(class_scope:LoginResp)
    private static final message.Login.LoginResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.Login.LoginResp();
    }

    public static message.Login.LoginResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginResp>
        PARSER = new com.google.protobuf.AbstractParser<LoginResp>() {
      @java.lang.Override
      public LoginResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LoginResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public message.Login.LoginResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LoginReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LoginResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Login.proto\"(\n\010LoginReq\022\017\n\007account\030\001 \001" +
      "(\t\022\013\n\003pwd\030\002 \001(\t\"S\n\tLoginResp\022\017\n\007rltCode\030" +
      "\001 \001(\005\022\022\n\nserverTime\030\002 \001(\003\022\017\n\007account\030\003 \001" +
      "(\t\022\020\n\010playerId\030\004 \001(\tB\t\n\007messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_LoginReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LoginReq_descriptor,
        new java.lang.String[] { "Account", "Pwd", });
    internal_static_LoginResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoginResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_LoginResp_descriptor,
        new java.lang.String[] { "RltCode", "ServerTime", "Account", "PlayerId", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
