// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Player.proto
// Protobuf Java Version: 4.27.2

package message;

public final class Player {
  private Player() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Player.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerBaseInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerBaseInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 玩家ID
     * </pre>
     *
     * <code>string playerId = 1;</code>
     * @return The playerId.
     */
    java.lang.String getPlayerId();
    /**
     * <pre>
     * 玩家ID
     * </pre>
     *
     * <code>string playerId = 1;</code>
     * @return The bytes for playerId.
     */
    com.google.protobuf.ByteString
        getPlayerIdBytes();

    /**
     * <pre>
     * 名字
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * 名字
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 钻石
     * </pre>
     *
     * <code>int32 diamond = 3;</code>
     * @return The diamond.
     */
    int getDiamond();
  }
  /**
   * Protobuf type {@code PlayerBaseInfo}
   */
  public static final class PlayerBaseInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PlayerBaseInfo)
      PlayerBaseInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        PlayerBaseInfo.class.getName());
    }
    // Use PlayerBaseInfo.newBuilder() to construct.
    private PlayerBaseInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PlayerBaseInfo() {
      playerId_ = "";
      name_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.Player.internal_static_PlayerBaseInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.Player.internal_static_PlayerBaseInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.Player.PlayerBaseInfo.class, message.Player.PlayerBaseInfo.Builder.class);
    }

    public static final int PLAYERID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object playerId_ = "";
    /**
     * <pre>
     * 玩家ID
     * </pre>
     *
     * <code>string playerId = 1;</code>
     * @return The playerId.
     */
    @java.lang.Override
    public java.lang.String getPlayerId() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        playerId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 玩家ID
     * </pre>
     *
     * <code>string playerId = 1;</code>
     * @return The bytes for playerId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlayerIdBytes() {
      java.lang.Object ref = playerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <pre>
     * 名字
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 名字
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIAMOND_FIELD_NUMBER = 3;
    private int diamond_ = 0;
    /**
     * <pre>
     * 钻石
     * </pre>
     *
     * <code>int32 diamond = 3;</code>
     * @return The diamond.
     */
    @java.lang.Override
    public int getDiamond() {
      return diamond_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, playerId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (diamond_ != 0) {
        output.writeInt32(3, diamond_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(playerId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, playerId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (diamond_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, diamond_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.Player.PlayerBaseInfo)) {
        return super.equals(obj);
      }
      message.Player.PlayerBaseInfo other = (message.Player.PlayerBaseInfo) obj;

      if (!getPlayerId()
          .equals(other.getPlayerId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getDiamond()
          != other.getDiamond()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PLAYERID_FIELD_NUMBER;
      hash = (53 * hash) + getPlayerId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DIAMOND_FIELD_NUMBER;
      hash = (53 * hash) + getDiamond();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.Player.PlayerBaseInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Player.PlayerBaseInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Player.PlayerBaseInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Player.PlayerBaseInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Player.PlayerBaseInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Player.PlayerBaseInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Player.PlayerBaseInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Player.PlayerBaseInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static message.Player.PlayerBaseInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static message.Player.PlayerBaseInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Player.PlayerBaseInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Player.PlayerBaseInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.Player.PlayerBaseInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerBaseInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerBaseInfo)
        message.Player.PlayerBaseInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.Player.internal_static_PlayerBaseInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.Player.internal_static_PlayerBaseInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.Player.PlayerBaseInfo.class, message.Player.PlayerBaseInfo.Builder.class);
      }

      // Construct using message.Player.PlayerBaseInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        playerId_ = "";
        name_ = "";
        diamond_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.Player.internal_static_PlayerBaseInfo_descriptor;
      }

      @java.lang.Override
      public message.Player.PlayerBaseInfo getDefaultInstanceForType() {
        return message.Player.PlayerBaseInfo.getDefaultInstance();
      }

      @java.lang.Override
      public message.Player.PlayerBaseInfo build() {
        message.Player.PlayerBaseInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public message.Player.PlayerBaseInfo buildPartial() {
        message.Player.PlayerBaseInfo result = new message.Player.PlayerBaseInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(message.Player.PlayerBaseInfo result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.playerId_ = playerId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.diamond_ = diamond_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.Player.PlayerBaseInfo) {
          return mergeFrom((message.Player.PlayerBaseInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.Player.PlayerBaseInfo other) {
        if (other == message.Player.PlayerBaseInfo.getDefaultInstance()) return this;
        if (!other.getPlayerId().isEmpty()) {
          playerId_ = other.playerId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getDiamond() != 0) {
          setDiamond(other.getDiamond());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                playerId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                diamond_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object playerId_ = "";
      /**
       * <pre>
       * 玩家ID
       * </pre>
       *
       * <code>string playerId = 1;</code>
       * @return The playerId.
       */
      public java.lang.String getPlayerId() {
        java.lang.Object ref = playerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          playerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 玩家ID
       * </pre>
       *
       * <code>string playerId = 1;</code>
       * @return The bytes for playerId.
       */
      public com.google.protobuf.ByteString
          getPlayerIdBytes() {
        java.lang.Object ref = playerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 玩家ID
       * </pre>
       *
       * <code>string playerId = 1;</code>
       * @param value The playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        playerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 玩家ID
       * </pre>
       *
       * <code>string playerId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlayerId() {
        playerId_ = getDefaultInstance().getPlayerId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 玩家ID
       * </pre>
       *
       * <code>string playerId = 1;</code>
       * @param value The bytes for playerId to set.
       * @return This builder for chaining.
       */
      public Builder setPlayerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        playerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 名字
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 名字
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 名字
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 名字
       * </pre>
       *
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 名字
       * </pre>
       *
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int diamond_ ;
      /**
       * <pre>
       * 钻石
       * </pre>
       *
       * <code>int32 diamond = 3;</code>
       * @return The diamond.
       */
      @java.lang.Override
      public int getDiamond() {
        return diamond_;
      }
      /**
       * <pre>
       * 钻石
       * </pre>
       *
       * <code>int32 diamond = 3;</code>
       * @param value The diamond to set.
       * @return This builder for chaining.
       */
      public Builder setDiamond(int value) {

        diamond_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 钻石
       * </pre>
       *
       * <code>int32 diamond = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDiamond() {
        bitField0_ = (bitField0_ & ~0x00000004);
        diamond_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PlayerBaseInfo)
    }

    // @@protoc_insertion_point(class_scope:PlayerBaseInfo)
    private static final message.Player.PlayerBaseInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.Player.PlayerBaseInfo();
    }

    public static message.Player.PlayerBaseInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerBaseInfo>
        PARSER = new com.google.protobuf.AbstractParser<PlayerBaseInfo>() {
      @java.lang.Override
      public PlayerBaseInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PlayerBaseInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerBaseInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public message.Player.PlayerBaseInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerDataRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerDataResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 玩家基本信息
     * </pre>
     *
     * <code>.PlayerBaseInfo baseInfo = 1;</code>
     * @return Whether the baseInfo field is set.
     */
    boolean hasBaseInfo();
    /**
     * <pre>
     * 玩家基本信息
     * </pre>
     *
     * <code>.PlayerBaseInfo baseInfo = 1;</code>
     * @return The baseInfo.
     */
    message.Player.PlayerBaseInfo getBaseInfo();
    /**
     * <pre>
     * 玩家基本信息
     * </pre>
     *
     * <code>.PlayerBaseInfo baseInfo = 1;</code>
     */
    message.Player.PlayerBaseInfoOrBuilder getBaseInfoOrBuilder();
  }
  /**
   * Protobuf type {@code PlayerDataResp}
   */
  public static final class PlayerDataResp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PlayerDataResp)
      PlayerDataRespOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        PlayerDataResp.class.getName());
    }
    // Use PlayerDataResp.newBuilder() to construct.
    private PlayerDataResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PlayerDataResp() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.Player.internal_static_PlayerDataResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.Player.internal_static_PlayerDataResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.Player.PlayerDataResp.class, message.Player.PlayerDataResp.Builder.class);
    }

    private int bitField0_;
    public static final int BASEINFO_FIELD_NUMBER = 1;
    private message.Player.PlayerBaseInfo baseInfo_;
    /**
     * <pre>
     * 玩家基本信息
     * </pre>
     *
     * <code>.PlayerBaseInfo baseInfo = 1;</code>
     * @return Whether the baseInfo field is set.
     */
    @java.lang.Override
    public boolean hasBaseInfo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 玩家基本信息
     * </pre>
     *
     * <code>.PlayerBaseInfo baseInfo = 1;</code>
     * @return The baseInfo.
     */
    @java.lang.Override
    public message.Player.PlayerBaseInfo getBaseInfo() {
      return baseInfo_ == null ? message.Player.PlayerBaseInfo.getDefaultInstance() : baseInfo_;
    }
    /**
     * <pre>
     * 玩家基本信息
     * </pre>
     *
     * <code>.PlayerBaseInfo baseInfo = 1;</code>
     */
    @java.lang.Override
    public message.Player.PlayerBaseInfoOrBuilder getBaseInfoOrBuilder() {
      return baseInfo_ == null ? message.Player.PlayerBaseInfo.getDefaultInstance() : baseInfo_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getBaseInfo());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getBaseInfo());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.Player.PlayerDataResp)) {
        return super.equals(obj);
      }
      message.Player.PlayerDataResp other = (message.Player.PlayerDataResp) obj;

      if (hasBaseInfo() != other.hasBaseInfo()) return false;
      if (hasBaseInfo()) {
        if (!getBaseInfo()
            .equals(other.getBaseInfo())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasBaseInfo()) {
        hash = (37 * hash) + BASEINFO_FIELD_NUMBER;
        hash = (53 * hash) + getBaseInfo().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.Player.PlayerDataResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Player.PlayerDataResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Player.PlayerDataResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Player.PlayerDataResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Player.PlayerDataResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Player.PlayerDataResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Player.PlayerDataResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Player.PlayerDataResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static message.Player.PlayerDataResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static message.Player.PlayerDataResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Player.PlayerDataResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Player.PlayerDataResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.Player.PlayerDataResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerDataResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerDataResp)
        message.Player.PlayerDataRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.Player.internal_static_PlayerDataResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.Player.internal_static_PlayerDataResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.Player.PlayerDataResp.class, message.Player.PlayerDataResp.Builder.class);
      }

      // Construct using message.Player.PlayerDataResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getBaseInfoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        baseInfo_ = null;
        if (baseInfoBuilder_ != null) {
          baseInfoBuilder_.dispose();
          baseInfoBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.Player.internal_static_PlayerDataResp_descriptor;
      }

      @java.lang.Override
      public message.Player.PlayerDataResp getDefaultInstanceForType() {
        return message.Player.PlayerDataResp.getDefaultInstance();
      }

      @java.lang.Override
      public message.Player.PlayerDataResp build() {
        message.Player.PlayerDataResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public message.Player.PlayerDataResp buildPartial() {
        message.Player.PlayerDataResp result = new message.Player.PlayerDataResp(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(message.Player.PlayerDataResp result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.baseInfo_ = baseInfoBuilder_ == null
              ? baseInfo_
              : baseInfoBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.Player.PlayerDataResp) {
          return mergeFrom((message.Player.PlayerDataResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.Player.PlayerDataResp other) {
        if (other == message.Player.PlayerDataResp.getDefaultInstance()) return this;
        if (other.hasBaseInfo()) {
          mergeBaseInfo(other.getBaseInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getBaseInfoFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private message.Player.PlayerBaseInfo baseInfo_;
      private com.google.protobuf.SingleFieldBuilder<
          message.Player.PlayerBaseInfo, message.Player.PlayerBaseInfo.Builder, message.Player.PlayerBaseInfoOrBuilder> baseInfoBuilder_;
      /**
       * <pre>
       * 玩家基本信息
       * </pre>
       *
       * <code>.PlayerBaseInfo baseInfo = 1;</code>
       * @return Whether the baseInfo field is set.
       */
      public boolean hasBaseInfo() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * 玩家基本信息
       * </pre>
       *
       * <code>.PlayerBaseInfo baseInfo = 1;</code>
       * @return The baseInfo.
       */
      public message.Player.PlayerBaseInfo getBaseInfo() {
        if (baseInfoBuilder_ == null) {
          return baseInfo_ == null ? message.Player.PlayerBaseInfo.getDefaultInstance() : baseInfo_;
        } else {
          return baseInfoBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 玩家基本信息
       * </pre>
       *
       * <code>.PlayerBaseInfo baseInfo = 1;</code>
       */
      public Builder setBaseInfo(message.Player.PlayerBaseInfo value) {
        if (baseInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          baseInfo_ = value;
        } else {
          baseInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 玩家基本信息
       * </pre>
       *
       * <code>.PlayerBaseInfo baseInfo = 1;</code>
       */
      public Builder setBaseInfo(
          message.Player.PlayerBaseInfo.Builder builderForValue) {
        if (baseInfoBuilder_ == null) {
          baseInfo_ = builderForValue.build();
        } else {
          baseInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 玩家基本信息
       * </pre>
       *
       * <code>.PlayerBaseInfo baseInfo = 1;</code>
       */
      public Builder mergeBaseInfo(message.Player.PlayerBaseInfo value) {
        if (baseInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            baseInfo_ != null &&
            baseInfo_ != message.Player.PlayerBaseInfo.getDefaultInstance()) {
            getBaseInfoBuilder().mergeFrom(value);
          } else {
            baseInfo_ = value;
          }
        } else {
          baseInfoBuilder_.mergeFrom(value);
        }
        if (baseInfo_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * 玩家基本信息
       * </pre>
       *
       * <code>.PlayerBaseInfo baseInfo = 1;</code>
       */
      public Builder clearBaseInfo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        baseInfo_ = null;
        if (baseInfoBuilder_ != null) {
          baseInfoBuilder_.dispose();
          baseInfoBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 玩家基本信息
       * </pre>
       *
       * <code>.PlayerBaseInfo baseInfo = 1;</code>
       */
      public message.Player.PlayerBaseInfo.Builder getBaseInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBaseInfoFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 玩家基本信息
       * </pre>
       *
       * <code>.PlayerBaseInfo baseInfo = 1;</code>
       */
      public message.Player.PlayerBaseInfoOrBuilder getBaseInfoOrBuilder() {
        if (baseInfoBuilder_ != null) {
          return baseInfoBuilder_.getMessageOrBuilder();
        } else {
          return baseInfo_ == null ?
              message.Player.PlayerBaseInfo.getDefaultInstance() : baseInfo_;
        }
      }
      /**
       * <pre>
       * 玩家基本信息
       * </pre>
       *
       * <code>.PlayerBaseInfo baseInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          message.Player.PlayerBaseInfo, message.Player.PlayerBaseInfo.Builder, message.Player.PlayerBaseInfoOrBuilder> 
          getBaseInfoFieldBuilder() {
        if (baseInfoBuilder_ == null) {
          baseInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              message.Player.PlayerBaseInfo, message.Player.PlayerBaseInfo.Builder, message.Player.PlayerBaseInfoOrBuilder>(
                  getBaseInfo(),
                  getParentForChildren(),
                  isClean());
          baseInfo_ = null;
        }
        return baseInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:PlayerDataResp)
    }

    // @@protoc_insertion_point(class_scope:PlayerDataResp)
    private static final message.Player.PlayerDataResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.Player.PlayerDataResp();
    }

    public static message.Player.PlayerDataResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerDataResp>
        PARSER = new com.google.protobuf.AbstractParser<PlayerDataResp>() {
      @java.lang.Override
      public PlayerDataResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PlayerDataResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerDataResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public message.Player.PlayerDataResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerBaseInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerBaseInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerDataResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerDataResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Player.proto\"A\n\016PlayerBaseInfo\022\020\n\010play" +
      "erId\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\017\n\007diamond\030\003 \001(" +
      "\005\"3\n\016PlayerDataResp\022!\n\010baseInfo\030\001 \001(\0132\017." +
      "PlayerBaseInfoB\t\n\007messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PlayerBaseInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerBaseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PlayerBaseInfo_descriptor,
        new java.lang.String[] { "PlayerId", "Name", "Diamond", });
    internal_static_PlayerDataResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PlayerDataResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PlayerDataResp_descriptor,
        new java.lang.String[] { "BaseInfo", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
