// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Territory.proto
// Protobuf Java Version: 4.27.2

package message;

public final class Territory {
  private Territory() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Territory.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlayerTerritoryRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerTerritoryResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 解锁地块ID
     * </pre>
     *
     * <code>repeated int32 blockId = 1;</code>
     * @return A list containing the blockId.
     */
    java.util.List<java.lang.Integer> getBlockIdList();
    /**
     * <pre>
     * 解锁地块ID
     * </pre>
     *
     * <code>repeated int32 blockId = 1;</code>
     * @return The count of blockId.
     */
    int getBlockIdCount();
    /**
     * <pre>
     * 解锁地块ID
     * </pre>
     *
     * <code>repeated int32 blockId = 1;</code>
     * @param index The index of the element to return.
     * @return The blockId at the given index.
     */
    int getBlockId(int index);
  }
  /**
   * Protobuf type {@code PlayerTerritoryResp}
   */
  public static final class PlayerTerritoryResp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PlayerTerritoryResp)
      PlayerTerritoryRespOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        PlayerTerritoryResp.class.getName());
    }
    // Use PlayerTerritoryResp.newBuilder() to construct.
    private PlayerTerritoryResp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PlayerTerritoryResp() {
      blockId_ = emptyIntList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return message.Territory.internal_static_PlayerTerritoryResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return message.Territory.internal_static_PlayerTerritoryResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              message.Territory.PlayerTerritoryResp.class, message.Territory.PlayerTerritoryResp.Builder.class);
    }

    public static final int BLOCKID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.IntList blockId_ =
        emptyIntList();
    /**
     * <pre>
     * 解锁地块ID
     * </pre>
     *
     * <code>repeated int32 blockId = 1;</code>
     * @return A list containing the blockId.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getBlockIdList() {
      return blockId_;
    }
    /**
     * <pre>
     * 解锁地块ID
     * </pre>
     *
     * <code>repeated int32 blockId = 1;</code>
     * @return The count of blockId.
     */
    public int getBlockIdCount() {
      return blockId_.size();
    }
    /**
     * <pre>
     * 解锁地块ID
     * </pre>
     *
     * <code>repeated int32 blockId = 1;</code>
     * @param index The index of the element to return.
     * @return The blockId at the given index.
     */
    public int getBlockId(int index) {
      return blockId_.getInt(index);
    }
    private int blockIdMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getBlockIdList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(blockIdMemoizedSerializedSize);
      }
      for (int i = 0; i < blockId_.size(); i++) {
        output.writeInt32NoTag(blockId_.getInt(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < blockId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(blockId_.getInt(i));
        }
        size += dataSize;
        if (!getBlockIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        blockIdMemoizedSerializedSize = dataSize;
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof message.Territory.PlayerTerritoryResp)) {
        return super.equals(obj);
      }
      message.Territory.PlayerTerritoryResp other = (message.Territory.PlayerTerritoryResp) obj;

      if (!getBlockIdList()
          .equals(other.getBlockIdList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBlockIdCount() > 0) {
        hash = (37 * hash) + BLOCKID_FIELD_NUMBER;
        hash = (53 * hash) + getBlockIdList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static message.Territory.PlayerTerritoryResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Territory.PlayerTerritoryResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Territory.PlayerTerritoryResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Territory.PlayerTerritoryResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Territory.PlayerTerritoryResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static message.Territory.PlayerTerritoryResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static message.Territory.PlayerTerritoryResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Territory.PlayerTerritoryResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static message.Territory.PlayerTerritoryResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static message.Territory.PlayerTerritoryResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static message.Territory.PlayerTerritoryResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static message.Territory.PlayerTerritoryResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(message.Territory.PlayerTerritoryResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerTerritoryResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerTerritoryResp)
        message.Territory.PlayerTerritoryRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return message.Territory.internal_static_PlayerTerritoryResp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return message.Territory.internal_static_PlayerTerritoryResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                message.Territory.PlayerTerritoryResp.class, message.Territory.PlayerTerritoryResp.Builder.class);
      }

      // Construct using message.Territory.PlayerTerritoryResp.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        blockId_ = emptyIntList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return message.Territory.internal_static_PlayerTerritoryResp_descriptor;
      }

      @java.lang.Override
      public message.Territory.PlayerTerritoryResp getDefaultInstanceForType() {
        return message.Territory.PlayerTerritoryResp.getDefaultInstance();
      }

      @java.lang.Override
      public message.Territory.PlayerTerritoryResp build() {
        message.Territory.PlayerTerritoryResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public message.Territory.PlayerTerritoryResp buildPartial() {
        message.Territory.PlayerTerritoryResp result = new message.Territory.PlayerTerritoryResp(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(message.Territory.PlayerTerritoryResp result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          blockId_.makeImmutable();
          result.blockId_ = blockId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof message.Territory.PlayerTerritoryResp) {
          return mergeFrom((message.Territory.PlayerTerritoryResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(message.Territory.PlayerTerritoryResp other) {
        if (other == message.Territory.PlayerTerritoryResp.getDefaultInstance()) return this;
        if (!other.blockId_.isEmpty()) {
          if (blockId_.isEmpty()) {
            blockId_ = other.blockId_;
            blockId_.makeImmutable();
            bitField0_ |= 0x00000001;
          } else {
            ensureBlockIdIsMutable();
            blockId_.addAll(other.blockId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int v = input.readInt32();
                ensureBlockIdIsMutable();
                blockId_.addInt(v);
                break;
              } // case 8
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                ensureBlockIdIsMutable();
                while (input.getBytesUntilLimit() > 0) {
                  blockId_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList blockId_ = emptyIntList();
      private void ensureBlockIdIsMutable() {
        if (!blockId_.isModifiable()) {
          blockId_ = makeMutableCopy(blockId_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <pre>
       * 解锁地块ID
       * </pre>
       *
       * <code>repeated int32 blockId = 1;</code>
       * @return A list containing the blockId.
       */
      public java.util.List<java.lang.Integer>
          getBlockIdList() {
        blockId_.makeImmutable();
        return blockId_;
      }
      /**
       * <pre>
       * 解锁地块ID
       * </pre>
       *
       * <code>repeated int32 blockId = 1;</code>
       * @return The count of blockId.
       */
      public int getBlockIdCount() {
        return blockId_.size();
      }
      /**
       * <pre>
       * 解锁地块ID
       * </pre>
       *
       * <code>repeated int32 blockId = 1;</code>
       * @param index The index of the element to return.
       * @return The blockId at the given index.
       */
      public int getBlockId(int index) {
        return blockId_.getInt(index);
      }
      /**
       * <pre>
       * 解锁地块ID
       * </pre>
       *
       * <code>repeated int32 blockId = 1;</code>
       * @param index The index to set the value at.
       * @param value The blockId to set.
       * @return This builder for chaining.
       */
      public Builder setBlockId(
          int index, int value) {

        ensureBlockIdIsMutable();
        blockId_.setInt(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 解锁地块ID
       * </pre>
       *
       * <code>repeated int32 blockId = 1;</code>
       * @param value The blockId to add.
       * @return This builder for chaining.
       */
      public Builder addBlockId(int value) {

        ensureBlockIdIsMutable();
        blockId_.addInt(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 解锁地块ID
       * </pre>
       *
       * <code>repeated int32 blockId = 1;</code>
       * @param values The blockId to add.
       * @return This builder for chaining.
       */
      public Builder addAllBlockId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureBlockIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, blockId_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 解锁地块ID
       * </pre>
       *
       * <code>repeated int32 blockId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlockId() {
        blockId_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PlayerTerritoryResp)
    }

    // @@protoc_insertion_point(class_scope:PlayerTerritoryResp)
    private static final message.Territory.PlayerTerritoryResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new message.Territory.PlayerTerritoryResp();
    }

    public static message.Territory.PlayerTerritoryResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerTerritoryResp>
        PARSER = new com.google.protobuf.AbstractParser<PlayerTerritoryResp>() {
      @java.lang.Override
      public PlayerTerritoryResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PlayerTerritoryResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerTerritoryResp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public message.Territory.PlayerTerritoryResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerTerritoryResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerTerritoryResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Territory.proto\"&\n\023PlayerTerritoryResp" +
      "\022\017\n\007blockId\030\001 \003(\005B\t\n\007messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PlayerTerritoryResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerTerritoryResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PlayerTerritoryResp_descriptor,
        new java.lang.String[] { "BlockId", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
